# Mod metadata for NeoForge - values from gradle.properties
modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''CTD Mod - Crafting The Dao.'''
