# Mod metadata for NeoForge - values from gradle.properties
modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''CTD Mod - Crafting The Dao.'''

# DÃ©pendances requises : Photon (VFX) et LDLib2 (lib de Photon)
[[dependencies]]
modId="ldlib2"
mandatory=true
versionRange="[2.0.3,)"
ordering="NONE"
side="BOTH"

[[dependencies]]
modId="photon"
mandatory=true
versionRange="[2.0.4,)"
ordering="NONE"
side="BOTH"
